import gl
import sys
import random
print(sys.version)
print(gl.version())
gl.resetdefaults()

##Gordon Networks
#gl.loadimage('//cifs.rc.ufl.edu/ufrc/rachaelseidler/tfettrow/Crunch_Code/MR_Templates/MNI_1mm.nii')
#gl.opacity(1,50)
#gl.overlayload("//cifs.rc.ufl.edu/ufrc/rachaelseidler/share/FromExternal/Research_Projects_UF/CRUNCH/MiM_Data/ROIs/Gordon2016_Auditory_mask")
#gl.minmax(1, 0.01,0.1)
#gl.colorname(1,'1red')
#gl.colorfromzero(1,1)
#gl.overlayload("//cifs.rc.ufl.edu/ufrc/rachaelseidler/share/FromExternal/Research_Projects_UF/CRUNCH/MiM_Data/ROIs/Gordon2016_CinguloOperc_mask")
#gl.minmax(2, 0.01,0.1)
#gl.colorname(2,'2green')
#gl.colorfromzero(2,1)
#gl.overlayload("//cifs.rc.ufl.edu/ufrc/rachaelseidler/share/FromExternal/Research_Projects_UF/CRUNCH/MiM_Data/ROIs/Gordon2016_CinguloParietal_mask")
#gl.minmax(3, 0.01,0.1)
#gl.colorname(3,'3blue')
#gl.colorfromzero(3,1)
#gl.overlayload("//cifs.rc.ufl.edu/ufrc/rachaelseidler/share/FromExternal/Research_Projects_UF/CRUNCH/MiM_Data/ROIs/Gordon2016_Default_mask")
#gl.minmax(4, 0.01,0.1)
#gl.colorname(4,'4hot')
#gl.colorfromzero(4,1)
#gl.overlayload("//cifs.rc.ufl.edu/ufrc/rachaelseidler/share/FromExternal/Research_Projects_UF/CRUNCH/MiM_Data/ROIs/Gordon2016_DorsalAttn_mask")
#gl.minmax(5, 0.01,0.1)
#gl.colorname(5,'5winter')
#gl.colorfromzero(5,1)
#gl.overlayload("//cifs.rc.ufl.edu/ufrc/rachaelseidler/share/FromExternal/Research_Projects_UF/CRUNCH/MiM_Data/ROIs/Gordon2016_FrontoParietal_mask")
#gl.minmax(6, 0.01,0.1)
#gl.colorname(6,'actc')
#gl.colorfromzero(6,1)
#gl.overlayload("//cifs.rc.ufl.edu/ufrc/rachaelseidler/share/FromExternal/Research_Projects_UF/CRUNCH/MiM_Data/ROIs/Gordon2016_None_mask")
#gl.minmax(7, 0.01,0.1)
#gl.colorname(7,'bronze')
#gl.colorfromzero(7,1)
#gl.overlayload("//cifs.rc.ufl.edu/ufrc/rachaelseidler/share/FromExternal/Research_Projects_UF/CRUNCH/MiM_Data/ROIs/Gordon2016_Salience_mask")
#gl.minmax(8, 0.01,0.1)
#gl.colorname(8,'CT_Bones')
#gl.colorfromzero(8,1)
#gl.overlayload("//cifs.rc.ufl.edu/ufrc/rachaelseidler/share/FromExternal/Research_Projects_UF/CRUNCH/MiM_Data/ROIs/Gordon2016_SMhand_mask")
#gl.minmax(9, 0.01,0.1)
#gl.colorname(9,'inferno')
#gl.colorfromzero(9,1)
#gl.overlayload("//cifs.rc.ufl.edu/ufrc/rachaelseidler/share/FromExternal/Research_Projects_UF/CRUNCH/MiM_Data/ROIs/Gordon2016_SMmouth_mask")
#gl.minmax(10, 0.01,0.1)
#gl.colorname(10,'x_rain')
#gl.colorfromzero(10,1)
#gl.overlayload("//cifs.rc.ufl.edu/ufrc/rachaelseidler/share/FromExternal/Research_Projects_UF/CRUNCH/MiM_Data/ROIs/Gordon2016_VentralAttn_mask")
#gl.minmax(11, 0.01,0.1)
#gl.colorname(11,'GE_color')
#gl.colorfromzero(11,1)
#gl.overlayload("//cifs.rc.ufl.edu/ufrc/rachaelseidler/share/FromExternal/Research_Projects_UF/CRUNCH/MiM_Data/ROIs/Gordon2016_Visual_mask")
#gl.minmax(12, 0.01,0.1)
#gl.colorname(12,'CT_Kidneys')
#gl.colorfromzero(12,1)

##Power Networks
gl.loadimage('//cifs.rc.ufl.edu/ufrc/rachaelseidler/tfettrow/Crunch_Code/MR_Templates/MNI_1mm.nii')
gl.opacity(1,50)
gl.overlayload("//cifs.rc.ufl.edu/ufrc/rachaelseidler/share/FromExternal/Research_Projects_UF/CRUNCH/MiM_Data/ROIs/Power2011_Auditory_mask")
gl.minmax(1, 0.01,0.1)
gl.colorname(1,'1red')
gl.colorfromzero(1,1)
gl.overlayload("//cifs.rc.ufl.edu/ufrc/rachaelseidler/share/FromExternal/Research_Projects_UF/CRUNCH/MiM_Data/ROIs/Power2011_Cingulo-opercular_Control_mask")
gl.minmax(2, 0.01,0.1)
gl.colorname(2,'2green')
gl.colorfromzero(2,1)
gl.overlayload("//cifs.rc.ufl.edu/ufrc/rachaelseidler/share/FromExternal/Research_Projects_UF/CRUNCH/MiM_Data/ROIs/Power2011_Default_mode_mask")
gl.minmax(3, 0.01,0.1)
gl.colorname(3,'3blue')
gl.colorfromzero(3,1)
gl.overlayload("//cifs.rc.ufl.edu/ufrc/rachaelseidler/share/FromExternal/Research_Projects_UF/CRUNCH/MiM_Data/ROIs/Power2011_Dorsal_attention_mask")
gl.minmax(4, 0.01,0.1)
gl.colorname(4,'4hot')
gl.colorfromzero(4,1)
gl.overlayload("//cifs.rc.ufl.edu/ufrc/rachaelseidler/share/FromExternal/Research_Projects_UF/CRUNCH/MiM_Data/ROIs/Power2011_Fronto-parietal_Task_Control_mask")
gl.minmax(5, 0.01,0.1)
gl.colorname(5,'5winter')
gl.colorfromzero(5,1)
gl.overlayload("//cifs.rc.ufl.edu/ufrc/rachaelseidler/share/FromExternal/Research_Projects_UF/CRUNCH/MiM_Data/ROIs/Power2011_RetrosplenialTemporal_mask")
gl.minmax(6, 0.01,0.1)
gl.colorname(6,'actc')
gl.colorfromzero(6,1)
gl.overlayload("//cifs.rc.ufl.edu/ufrc/rachaelseidler/share/FromExternal/Research_Projects_UF/CRUNCH/MiM_Data/ROIs/Power2011_Salience_mask")
gl.minmax(7, 0.01,0.1)
gl.colorname(7,'bronze')
gl.colorfromzero(7,1)
gl.overlayload("//cifs.rc.ufl.edu/ufrc/rachaelseidler/share/FromExternal/Research_Projects_UF/CRUNCH/MiM_Data/ROIs/Power2011_Sensorimotor_Hand_mask")
gl.minmax(8, 0.01,0.1)
gl.colorname(8,'CT_Bones')
gl.colorfromzero(8,1)
gl.overlayload("//cifs.rc.ufl.edu/ufrc/rachaelseidler/share/FromExternal/Research_Projects_UF/CRUNCH/MiM_Data/ROIs/Power2011_Sensorimotor_Mouth_mask")
gl.minmax(9, 0.01,0.1)
gl.colorname(9,'inferno')
gl.colorfromzero(9,1)
gl.overlayload("//cifs.rc.ufl.edu/ufrc/rachaelseidler/share/FromExternal/Research_Projects_UF/CRUNCH/MiM_Data/ROIs/Power2011_Ventral_attention_mask")
gl.minmax(10, 0.01,0.1)
gl.colorname(10,'GE_color')
gl.colorfromzero(10,1)
gl.overlayload("//cifs.rc.ufl.edu/ufrc/rachaelseidler/share/FromExternal/Research_Projects_UF/CRUNCH/MiM_Data/ROIs/Power2011_Visual_mask")
gl.minmax(11, 0.01,0.1)
gl.colorname(11,'CT_Kidneys')
gl.colorfromzero(11,1)

gl.colorbarposition(0)
#"a"xial, "c"oronal and "s"agittal "r"enderings
gl.mosaic("A R 0 C R 0 S R 0; A R -0 C R -0 S R -0");